name:                type-theory-homework
version:             0.1.0.0
github:              "vadimsemenov/type-theory-homework"
license:             BSD3
author:              "Vadim Semenov"
maintainer:          "semenov@rain.ifmo.ru"
copyright:           "Copyright: (c) 2017 Vadim Semenov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/vadimsemenov/type-theory-homework#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text

library:
  source-dirs: src

executables:
  type-theory-homework-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-theory-homework

tests:
  type-theory-homework-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-theory-homework
    - hspec
